// Package flow aggregates packets into connections.
//
// This is the load-bearing decision of the whole tool: we never ship packets to
// the UI. A moderately busy laptop emits a few thousand a second, which no
// graph can render and no human can read. Packets fold into flows keyed by
// 5-tuple, and the UI gets a snapshot at 1Hz with counters. Packet-level detail
// stays available for drill-down, but it is never the default view.
package flow

import (
	"crypto/sha1"
	"encoding/hex"
	"net"
	"net/netip"
	"sync"
	"time"

	"ohmyosi/internal/decode"
	"ohmyosi/internal/pktap"
)

type State string

const (
	StateNew    State = "new"
	StateActive State = "active"
	StateClosed State = "closed"
)

// Key identifies a connection. Always oriented local-first, so both directions
// of the same conversation land on one row.
type Key struct {
	Proto  decode.Proto
	Local  netip.AddrPort
	Remote netip.AddrPort
}

// Flow is one connection's accumulated state.
type Flow struct {
	Key
	ID    string
	PID   int32
	Comm  string
	EPID  int32
	EComm string
	Iface string

	FirstSeen time.Time
	LastSeen  time.Time

	BytesUp   uint64
	BytesDown uint64
	PktsUp    uint64
	PktsDown  uint64

	SNI string // straight off the ClientHello, when we saw one
	// JA4 is the TLS client fingerprint of whatever opened this connection,
	// from the ClientHello. It names the software, not the destination, and it
	// survives ECH - so it is the one identity signal left when the SNI is gone.
	JA4 string
	// SawSYN means we witnessed this connection being opened. When false, the
	// flow predates the daemon: its handshake, and therefore its SNI, happened
	// before we were watching. That is the honest explanation for most unnamed
	// TCP flows, and it is worth stating rather than leaving a blank.
	SawSYN bool
	// Queries are the names seen being resolved over this flow. Only ever
	// populated for a resolver's own connections, and the thing that makes them
	// legible: the destination is one hop, the names are the real endpoints.
	Queries []string
	State   State

	// Self marks flows generated by ohmyosi itself, chiefly its own reverse
	// DNS lookups. A monitor that shows up in its own graph is funny once and
	// noise forever, so the UI filters these by default.
	Self bool

	// PreExisting marks a TCP flow whose opening handshake we never saw,
	// because it was already established when the daemon started. It is the
	// honest reason such a flow has no SNI.
	PreExisting bool

	dirty bool
}

// Table is the live set of flows.
type Table struct {
	mu     sync.RWMutex
	flows  map[Key]*Flow
	local  map[netip.Addr]bool
	selfPI int32

	// SelfPort is ohmyosi's own listen port. Traffic to it is the UI watching
	// the daemon, and it was cluttering the top of the table with the tool
	// observing itself.
	SelfPort uint16

	IdleTimeout   time.Duration // silent flows are dropped after this
	ClosedLinger  time.Duration // how long a FIN/RST flow stays visible
	lastLocalScan time.Time

	// lastTs is the newest packet timestamp seen. Expiry runs against this
	// rather than the wall clock, because the two are not the same thing when
	// replaying a saved capture: a file recorded a minute ago would have every
	// flow instantly older than IdleTimeout and get wiped before anything
	// could be reported. Live, the two are identical.
	lastTs time.Time
}

func NewTable(selfPID int32) *Table {
	t := &Table{
		flows:        make(map[Key]*Flow, 512),
		local:        make(map[netip.Addr]bool, 16),
		selfPI:       selfPID,
		IdleTimeout:  90 * time.Second,
		ClosedLinger: 15 * time.Second,
	}
	t.refreshLocal()
	return t
}

// refreshLocal rebuilds the set of addresses that count as "this machine".
// It is rescanned periodically on purpose: IPv6 privacy addresses rotate,
// DHCP leases change, and VPN interfaces appear mid-session. A stale set makes
// direction detection silently wrong, which is worse than slow.
func (t *Table) refreshLocal() {
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return
	}
	next := make(map[netip.Addr]bool, len(addrs))
	for _, a := range addrs {
		if ipn, ok := a.(*net.IPNet); ok {
			if ip, ok := netip.AddrFromSlice(ipn.IP); ok {
				next[ip.Unmap()] = true
			}
		}
	}
	t.local = next
	t.lastLocalScan = time.Now()
}

func (t *Table) isLocal(a netip.Addr) bool {
	return t.local[a] || a.IsLoopback() || a.IsLinkLocalUnicast()
}

// Observe folds one packet into the table.
func (t *Table) Observe(o *decode.Obs) {
	if o == nil || !o.Src.IsValid() || !o.Dst.IsValid() {
		return
	}
	t.mu.Lock()
	defer t.mu.Unlock()

	if time.Since(t.lastLocalScan) > 30*time.Second {
		t.refreshLocal()
	}

	// Orientation. The kernel's direction flag is a hint, not gospel: it is
	// missing on some interface types and wrong on a few. Address membership
	// wins when we can determine it.
	var local, remote netip.AddrPort
	var outbound bool
	srcLocal, dstLocal := t.isLocal(o.Src), t.isLocal(o.Dst)
	switch {
	case srcLocal && !dstLocal:
		outbound = true
	case dstLocal && !srcLocal:
		outbound = false
	case o.Dir == pktap.DirOut:
		outbound = true
	case o.Dir == pktap.DirIn:
		outbound = false
	default:
		// Both or neither local (loopback, VPN transit). Fall back to the
		// ephemeral-port heuristic: the higher port is almost always the
		// client side.
		outbound = o.SPort > o.DPort
	}
	if outbound {
		local = netip.AddrPortFrom(o.Src, o.SPort)
		remote = netip.AddrPortFrom(o.Dst, o.DPort)
	} else {
		local = netip.AddrPortFrom(o.Dst, o.DPort)
		remote = netip.AddrPortFrom(o.Src, o.SPort)
	}

	k := Key{Proto: o.Proto, Local: local, Remote: remote}
	f, ok := t.flows[k]
	if !ok {
		f = &Flow{
			Key: k, ID: flowID(k), FirstSeen: o.Ts,
			State: StateNew, Self: o.PID > 0 && o.PID == t.selfPI,
			// If the first packet we ever see on a TCP connection is not a
			// SYN, the handshake happened before we were watching.
			PreExisting: o.Proto == decode.TCP && !o.SYN,
		}
		t.flows[k] = f
	} else if f.State == StateNew {
		f.State = StateActive
	}

	// pktap only stamps a PID on one direction of a flow, so never overwrite a
	// known PID with the zero we get on the other side.
	if o.PID > 0 {
		f.PID, f.Comm = o.PID, o.Comm
		if o.PID == t.selfPI {
			f.Self = true
		}
	}
	if t.SelfPort != 0 && local.Addr().IsLoopback() && remote.Addr().IsLoopback() &&
		(local.Port() == t.SelfPort || remote.Port() == t.SelfPort) {
		f.Self = true
	}
	if o.EPID > 0 {
		f.EPID, f.EComm = o.EPID, o.EComm
		// ohmyosi's own lookups go out through mDNSResponder, so the socket PID
		// is the resolver's and only the effective PID is ours. Without this,
		// the tool's own DNS and RDAP traffic shows up unattributed and gets
		// scored as if it were something to worry about.
		if o.EPID == t.selfPI {
			f.Self = true
		}
	}
	if o.Iface != "" {
		f.Iface = o.Iface
	}
	if o.SNI != "" {
		f.SNI = o.SNI
	}
	if o.JA4 != "" {
		f.JA4 = o.JA4
	}

	n := uint64(o.WireLen)
	if outbound {
		f.BytesUp += n
		f.PktsUp++
	} else {
		f.BytesDown += n
		f.PktsDown++
	}
	if o.SYN {
		f.SawSYN = true
		f.PreExisting = false
	}
	for _, q := range o.Questions {
		f.addQuery(q)
	}
	if o.FIN || o.RST {
		f.State = StateClosed
	}
	f.LastSeen = o.Ts
	f.dirty = true
	if o.Ts.After(t.lastTs) {
		t.lastTs = o.Ts
	}
}

// Now is the capture's clock: the newest packet timestamp seen, or the wall
// clock before any packet has arrived. Pass it to Expire.
func (t *Table) Now() time.Time {
	t.mu.RLock()
	defer t.mu.RUnlock()
	if t.lastTs.IsZero() {
		return time.Now()
	}
	return t.lastTs
}

// DisplayPID and DisplayComm live in attrib.go: crediting the effective PID
// only for known system resolvers, not for every flow that happens to carry one.

// maxQueries caps what one resolver flow remembers. A busy machine resolves
// thousands of names; the recent ones are what make the flow readable, and an
// unbounded list is a memory leak with a UI attached.
const maxQueries = 24

func (f *Flow) addQuery(name string) {
	if name == "" {
		return
	}
	for _, q := range f.Queries {
		if q == name {
			return
		}
	}
	if len(f.Queries) >= maxQueries {
		copy(f.Queries, f.Queries[1:])
		f.Queries = f.Queries[:maxQueries-1]
	}
	f.Queries = append(f.Queries, name)
}

// Snapshot returns flows touched since the last call, and clears the dirty
// marks. Sending only what changed keeps a busy machine's update under a few KB
// per tick instead of re-serializing the whole table every second.
func (t *Table) Snapshot() []Flow {
	t.mu.Lock()
	defer t.mu.Unlock()
	out := make([]Flow, 0, 64)
	for _, f := range t.flows {
		if f.dirty {
			f.dirty = false
			out = append(out, *f)
		}
	}
	return out
}

// All returns every live flow, for a client that just connected.
func (t *Table) All() []Flow {
	t.mu.RLock()
	defer t.mu.RUnlock()
	out := make([]Flow, 0, len(t.flows))
	for _, f := range t.flows {
		out = append(out, *f)
	}
	return out
}

// Expire drops flows that have gone quiet. Returns the IDs removed so the UI
// can retire those nodes instead of leaving them on the canvas forever.
func (t *Table) Expire(now time.Time) []string {
	t.mu.Lock()
	defer t.mu.Unlock()
	var gone []string
	for k, f := range t.flows {
		limit := t.IdleTimeout
		if f.State == StateClosed {
			limit = t.ClosedLinger
		}
		if now.Sub(f.LastSeen) > limit {
			gone = append(gone, f.ID)
			delete(t.flows, k)
		}
	}
	return gone
}

// Seed inserts a flow discovered outside capture (e.g. lsof at startup).
func (t *Table) Seed(proto decode.Proto, local, remote netip.AddrPort, pid int32, comm string, sawSYN bool) {
	o := &decode.Obs{
		Ts: time.Now(), PID: pid, Comm: comm, Proto: proto,
		Src: local.Addr(), Dst: remote.Addr(),
		SPort: local.Port(), DPort: remote.Port(),
		SYN: sawSYN,
	}
	t.Observe(o)
	t.mu.Lock()
	k := Key{Proto: proto, Local: local, Remote: remote}
	if f, ok := t.flows[k]; ok && !sawSYN {
		f.PreExisting = true
	}
	t.mu.Unlock()
}

// PIDs returns the distinct processes currently holding flows.
func (t *Table) PIDs() []int32 {
	t.mu.RLock()
	defer t.mu.RUnlock()
	seen := make(map[int32]bool, 32)
	out := make([]int32, 0, 32)
	for _, f := range t.flows {
		pid := f.DisplayPID()
		if pid > 0 && !seen[pid] {
			seen[pid] = true
			out = append(out, pid)
		}
	}
	return out
}

// RemoteIPs returns the distinct remote addresses, for name resolution.
func (t *Table) RemoteIPs() []netip.Addr {
	t.mu.RLock()
	defer t.mu.RUnlock()
	seen := make(map[netip.Addr]bool, 64)
	out := make([]netip.Addr, 0, 64)
	for _, f := range t.flows {
		ip := f.Remote.Addr()
		if !seen[ip] {
			seen[ip] = true
			out = append(out, ip)
		}
	}
	return out
}

// flowID is stable across restarts for the same 5-tuple, which lets the UI keep
// a node pinned in place rather than having it jump when the daemon reconnects.
func flowID(k Key) string {
	h := sha1.New()
	h.Write([]byte(k.Proto))
	h.Write([]byte(k.Local.String()))
	h.Write([]byte(k.Remote.String()))
	return hex.EncodeToString(h.Sum(nil))[:16]
}
